export const IN_APP_NOTIFICATIONS_NODE_NAME = 'in-app-notifications' as const;

export const IN_APP_NOTIFICATIONS_SERVICE_IDENTIFIER =
    'NOTIFICATIONS_SERVICE_V1';
// 'IN_APP_NOTIFICATIONS_SERVICE';
