import * as z from 'zod';
export const ENTRIES = [
    'Alaska',
    'Alabama',
    'Arkansas',
    'American Samoa',
    'Arizona',
    'California',
    'Colorado',
    'Connecticut',
    'District of Columbia',
    'Delaware',
    'Florida',
    'Georgia',
    'Guam',
    'Hawaii',
    'Iowa',
    'Idaho',
    'Illinois',
    'Indiana',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Massachusetts',
    'Maryland',
    'Maine',
    'Michigan',
    'Minnesota',
    'Missouri',
    'Northern Mariana Islands',
    'Mississippi',
    'Montana',
    'National',
    'North Carolina',
    'North Dakota',
    'Nebraska',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'Nevada',
    'New York',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Puerto Rico',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Virginia',
    'Virgin Islands',
    'Vermont',
    'Washington',
    'Wisconsin',
    'West Virginia',
    'Wyoming',
] as const;

export const MAP = {
    ALASKA: 'Alaska',
    ALABAMA: 'Alabama',
    ARKANSAS: 'Arkansas',
    AMERICAN_SAMOA: 'American Samoa',
    ARIZONA: 'Arizona',
    CALIFORNIA: 'California',
    COLORADO: 'Colorado',
    CONNECTICUT: 'Connecticut',
    DISTRICT_OF_COLUMBIA: 'District of Columbia',
    DELAWARE: 'Delaware',
    FLORIDA: 'Florida',
    GEORGIA: 'Georgia',
    GUAM: 'Guam',
    HAWAII: 'Hawaii',
    IOWA: 'Iowa',
    IDAHO: 'Idaho',
    ILLINOIS: 'Illinois',
    INDIANA: 'Indiana',
    KANSAS: 'Kansas',
    KENTUCKY: 'Kentucky',
    LOUISIANA: 'Louisiana',
    MASSACHUSETTS: 'Massachusetts',
    MARYLAND: 'Maryland',
    MAINE: 'Maine',
    MICHIGAN: 'Michigan',
    MINNESOTA: 'Minnesota',
    MISSOURI: 'Missouri',
    NORTHERN_MARIANA_ISLANDS: 'Northern Mariana Islands',
    MISSISSIPPI: 'Mississippi',
    MONTANA: 'Montana',
    NATIONAL: 'National',
    NORTH_CAROLINA: 'North Carolina',
    NORTH_DAKOTA: 'North Dakota',
    NEBRASKA: 'Nebraska',
    NEW_HAMPSHIRE: 'New Hampshire',
    NEW_JERSEY: 'New Jersey',
    NEW_MEXICO: 'New Mexico',
    NEVADA: 'Nevada',
    NEW_YORK: 'New York',
    OHIO: 'Ohio',
    OKLAHOMA: 'Oklahoma',
    OREGON: 'Oregon',
    PENNSYLVANIA: 'Pennsylvania',
    PUERTO_RICO: 'Puerto Rico',
    RHODE_ISLAND: 'Rhode Island',
    SOUTH_CAROLINA: 'South Carolina',
    SOUTH_DAKOTA: 'South Dakota',
    TENNESSEE: 'Tennessee',
    TEXAS: 'Texas',
    UTAH: 'Utah',
    VIRGINIA: 'Virginia',
    VIRGIN_ISLANDS: 'Virgin Islands',
    VERMONT: 'Vermont',
    WASHINGTON: 'Washington',
    WISCONSIN: 'Wisconsin',
    WEST_VIRGINIA: 'West Virginia',
    WYOMING: 'Wyoming',
} as const;

export const schema = z.enum(ENTRIES);

export type State = z.infer<typeof schema>;

export const validate = (value: unknown): State => {
    return schema.parse(value);
};

export const isValid = (value: unknown): value is State => {
    try {
        validate(value);
        return true;
    } catch {
        return false;
    }
};
